### ISSUE TITLE
react-native-reanimated@^2.12.0 Dependencies 

### ISSUE THREAD

**Issue by alextaikh** [jamsch/react-native-hanzi-writer#4]
I am using ReactNative Expo to develop. Having a lot of problem with the Dependencies Requirement withreact-native-reanimated@^2.12.0 . Any tips?

**Comment by jamsch** [comment]
Hey @alextaikh, apologies I haven't updated the README.md yet. The library supports the latest version of Expo 51 with react-native-reanimated v3.

**Comment by alextaikh** [comment]
Thanks.. I was having a lot of problem with that.  I ran an Expo Doctor and sort of fix it.

**Comment by alextaikh** [comment]
I am trying to working on integrating with AI tutor. Hey how do you write 你， and a Hanzi Writer popping up by AI Tutor :-)

**Comment by jamsch** [comment]
@alextaikh that sounds like a fun project! All the best!

**Comment by alextaikh** [comment]
Actually I am still having problem with dependencies issue with also react-native-svg

**Comment by jamsch** [comment]
@alextaikh 
You should be able to install it by typing: `npm install @jamsch/react-native-hanzi-writer --legacy-peer-deps`

I'll update the package soon so you won't need to do that though
